name: full_text_search
version: 0.8.0+3
homepage: https://github.com/SunnyApp/full_text_search
description: Full-text search that takes advantages of isolates to prevent locking the main thread
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  collection: ^1.16.0
  equatable: ^2.0.3
  logging: ^1.0.2
  meta: ^1.3.0
  sunny_dart: 
    path: /Users/ericm/sunny/player_rank/packages/sunny_dart
  dartxx: 
    path: /Users/ericm/sunny/player_rank/packages/dartxx
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
