name: full_text_search
version: 0.8.0+2
homepage: https://github.com/SunnyApp/full_text_search
description: Full-text search that takes advantages of isolates to prevent locking the main thread
environment: 
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  collection: ^1.15.0
  equatable: ^2.0.3
  logging: ^1.0.2
  meta: ^1.3.0
  sunny_dart: ^0.11.0+5
  dartxx: ^0.5.3+2
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
